### ISSUE TITLE
OpenStack VersionUp BATTLE

### ISSUE THREAD

**Issue by nwiizo** [nwiizo/cndt2019_openstack_versionup_battle#2]
[CloudNative Days Tokyo 2019/OpenStack Days Tokyo 2019 に協賛します！](https://hoscon.gmo.jp/events/2114/)にて

> ■ブース出展
GMOインターネットブースでは、
GMOインターネット新卒3年目　VS　GMOペパボ  プリンシパルエンジニア
『OpenStack バージョンアップ対決』を行います。
会期の2日間をかけて、チャレンジャー2名がOcata からPikeへのアップデートをどちらが早く行えるかについて競います。

ということでそのIssue

**Comment by nwiizo** [comment]
[OpenStackをアップグレードしたら心臓止まりかけた話](https://qiita.com/kentarosasaki/items/d1dac8cdaea68ae03bbe)を読み始めた。

**Comment by nwiizo** [comment]
[Ocata](https://releases.openstack.org/ocata/index.html)や[Pike](https://releases.openstack.org/pike/index.html)を見たり[Pike release](https://docs.openstack.org/releasenotes/openstack-manuals/pike.html)を見てフムフムとなってる。

**Comment by nwiizo** [comment]
[Upgrades](https://docs.openstack.org/operations-guide/ops-upgrades.html)を読んでいる。
上記のQiitaでは下記のような記述があるのだが実情が分らん。
```
Keystone -> Glance -> Nova -> Neutron
```

**Comment by nwiizo** [comment]
いろんな、ドキュメントがUbuntuベースで絶望している。

**Comment by nwiizo** [comment]
[OpenStack packages for RHEL and CentOS](https://docs.openstack.org/install-guide/environment-packages-rdo.html)
```
yum install centos-release-openstack-pike
```

とりあえず、実行

**Comment by nwiizo** [comment]
IPv6 を殺す。
```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
```

**Comment by nwiizo** [comment]
installをサボってしまったせいでプロセスの再起動がめちゃくちゃしんどいです。
各コンポーネントごとにまとめていく

**Comment by nwiizo** [comment]
[stop_keystone](https://github.com/openstack/devstack/blob/8ab64b3236c93c8449edf80165017898b83f1269/lib/keystone#L549)という関数にてプロセスをストップさせる。
実際の処理は下記になります。
```
if [ "$KEYSTONE_DEPLOY" == "mod_wsgi" ]; then
        disable_apache_site keystone
        restart_apache_server
    else
        stop_process keystone
    fi
```
実際に動作しているプロセスはこうなるので`mod_wsgi` 使ってるっぽいです。
```
# ps aux |grep wsgi:keystone
stack    15180  0.0  1.0 581428 85216 ?        Sl   Jul21   0:15 (wsgi:keystone- -DFOREGROUND
```

とかすればよいのですが
```
disable_apache_site keystone
enable_apache_site keystone
restart_apache_server
```

[run_process](https://github.com/openstack/devstack/blob/5e09df086c2eaca0f88c0c208992bc56d070581d/functions-common#L1582)を用いて

**Comment by nwiizo** [comment]
Bug 1493050 - ImportError: cannot import name base
https://bugzilla.redhat.com/show_bug.cgi?id=1493050

をやっていく

**Comment by nwiizo** [comment]
Error 発生しておりやっていく
```
2019-07-22 15:12:38.897270 mod_wsgi (pid=29488): Target WSGI script '/opt/stack/horizon/openstack_dashboard/wsgi/django.wsgi' cannot be loaded as Python module.
2019-07-22 15:12:38.897320 mod_wsgi (pid=29488): Exception occurred processing WSGI script '/opt/stack/horizon/openstack_dashboard/wsgi/django.wsgi'.
2019-07-22 15:12:38.897342 Traceback (most recent call last):
2019-07-22 15:12:38.897377   File "/opt/stack/horizon/openstack_dashboard/wsgi/django.wsgi", line 14, in <module>
2019-07-22 15:12:38.897409     application = get_wsgi_application()
2019-07-22 15:12:38.897422   File "/usr/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
2019-07-22 15:12:38.897438     django.setup()
2019-07-22 15:12:38.897445   File "/usr/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
2019-07-22 15:12:38.897456     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2019-07-22 15:12:38.897464   File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
2019-07-22 15:12:38.897483     self._setup(name)
2019-07-22 15:12:38.897494   File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
2019-07-22 15:12:38.897505     self._wrapped = Settings(settings_module)
2019-07-22 15:12:38.897511   File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
2019-07-22 15:12:38.897520     mod = importlib.import_module(self.SETTINGS_MODULE)
2019-07-22 15:12:38.897526   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
2019-07-22 15:12:38.897536     __import__(name)
2019-07-22 15:12:38.897542   File "/opt/stack/horizon/openstack_dashboard/settings.py", line 27, in <module>
2019-07-22 15:12:38.897553     from openstack_dashboard import exceptions
2019-07-22 15:12:38.897558   File "/opt/stack/horizon/openstack_dashboard/exceptions.py", line 25, in <module>
2019-07-22 15:12:38.897569     from requests import exceptions as requests
2019-07-22 15:12:38.897574   File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 43, in <module>
2019-07-22 15:12:38.897585     import urllib3
2019-07-22 15:12:38.897591   File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
2019-07-22 15:12:38.897601     from .connectionpool import (
2019-07-22 15:12:38.897606   File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 43, in <module>
2019-07-22 15:12:38.897616     from .util.url import get_host, Url, NORMALIZABLE_SCHEMES
2019-07-22 15:12:38.897634 ImportError: cannot import name NORMALIZABLE_SCHEMES
```

**Comment by nwiizo** [comment]
初期方針が劇的に失敗している気がしてきた。

**Comment by nwiizo** [comment]
一応、バージョンアップが終わった気がする。
```
Keystone -> Glance -> Nova -> Neutron -> Cinder -> Horizon
```

**Comment by nwiizo** [comment]
参考リンク集
https://docs.openstack.org/oslo.messaging/pike/admin/pika_driver.html
https://docs.openstack.org/install-guide/environment-packages-rdo.html

**Comment by nwiizo** [comment]
隣で昨日3時間ぐらい考えて見つけた方法を15分ぐらいでつぶやいてて恐怖する。

**Comment by nwiizo** [comment]
[devstack](https://github.com/nwiizo/cndt2019_openstack_versionup_battle/blob/master/docs/build_memo.md)が主導でのバージョンアップに劇的に向いてない説ある。

**Comment by nwiizo** [comment]
VMが吹っ飛んでた…。

**Comment by nwiizo** [comment]
あぁぁぁぁぁぁぁぁぁあああああ

**Comment by nwiizo** [comment]
隣ですごく時間のかかったトラブルシューティングを一瞬で解決しててすげぇぇえええってなるオタクになってる。
